[build]
  base = "website/react-landing"
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  # API Proxying - Specific to General
  from = "/api/admin/*"
  to = "http://174.138.93.172:3008/api/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "http://174.138.93.172:3007/api/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/user/*"
  to = "http://174.138.93.172:3007/api/user/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/detect"
  to = "http://174.138.93.172:3003/api/detect"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "http://174.138.93.172:3003/api/health"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "http://174.138.93.172:3003/api/:splat"
  status = 200
  force = true

[[redirects]]
  # Support Single Page Application (SPA) routing: 
  # Redirect all non-file requests to index.html
  from = "/*"
  to = "/index.html"
  status = 200
