[build]
  base = "website/react-landing"
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  # Support Single Page Application (SPA) routing: 
  # Redirect all requests to index.html if the file doesn't exist
  from = "/*"
  to = "/index.html"
  status = 200
